# Generated by Django 5.0.1 on 2024-03-19 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_alter_account_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='current_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
