# Generated by Django 5.0.1 on 2024-04-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_address_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_picture',
        ),
    ]
