# Generated by Django 5.0.1 on 2024-04-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
