# Generated by Django 5.0.1 on 2024-04-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
