# Generated by Django 5.0.1 on 2024-04-15 06:21

import django.core.validators
import watcheck.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_account_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_name]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_name]),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_town]),
        ),
    ]
