# Generated by Django 5.0.1 on 2024-03-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_image', models.ImageField(upload_to='')),
                ('brand_watch', models.CharField(max_length=30)),
                ('model_watch', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
