# Generated by Django 5.0.1 on 2024-03-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='watch_code',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
