# Generated by Django 5.0.1 on 2024-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_bag_watch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='watch_image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
