# Generated by Django 5.0.1 on 2024-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_order_watch_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='brand_watch',
            field=models.CharField(max_length=100),
        ),
    ]
