# Generated by Django 5.0.1 on 2024-04-08 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_order_brand_watch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='brand_watch',
        ),
        migrations.RemoveField(
            model_name='order',
            name='watch_image',
        ),
    ]
