# Generated by Django 5.0.1 on 2024-04-11 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_remove_order_brand_watch_remove_order_watch_image'),
        ('watch', '0003_alter_review_person_review_alter_review_rated_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_watch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='watch.watch'),
            preserve_default=False,
        ),
    ]
