# Generated by Django 5.0.1 on 2024-04-15 06:21

import django.core.validators
import watcheck.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_order_current_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_name]),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_name]),
        ),
        migrations.AlterField(
            model_name='order',
            name='town',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), watcheck.accounts.validators.only_letters_town]),
        ),
    ]
