# Generated by Django 5.0.1 on 2024-04-16 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_order_current_profile_and_more'),
        ('watch', '0006_alter_watch_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='current_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.watch'),
        ),
    ]
