# Generated by Django 5.0.1 on 2024-02-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='fourth_small_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='third_small_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
