# Generated by Django 5.0.1 on 2024-02-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='fourth_image',
            new_name='first_small_image',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='second_image',
            new_name='fourth_small_image',
        ),
        migrations.RenameField(
            model_name='watch',
            old_name='third_image',
            new_name='second_small_image',
        ),
        migrations.AddField(
            model_name='watch',
            name='third_small_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
