# Generated by Django 5.0.1 on 2024-02-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_alter_watch_fourth_small_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='case_diameter',
            field=models.IntegerField(),
        ),
    ]
