# Generated by Django 5.0.1 on 2024-04-15 20:01

import watcheck.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_alter_review_person_review_alter_review_rated_watch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brand',
            field=models.CharField(max_length=30, validators=[watcheck.common.validators.only_capital_letters]),
        ),
    ]
