# Generated by Django 5.0.1 on 2024-04-15 20:05

import watcheck.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_alter_watch_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='watch_code',
            field=models.CharField(max_length=20, validators=[watcheck.common.validators.only_capital_letters]),
        ),
    ]
