# Generated by Django 5.0.1 on 2024-04-16 20:08

import watcheck.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_alter_watch_watch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='brand',
            field=models.CharField(choices=[('ARNOLD & SON', 'ARNOLD & SON'), ('FESTINA', 'FESTINA'), ('LIGE', 'LIGE'), ('MVMT', 'MVMT'), ('FOSSIL', 'FOSSIL')], max_length=30, validators=[watcheck.common.validators.only_capital_letters]),
        ),
    ]
